### ISSUE TITLE
Publish new version to npm

### ISSUE THREAD

**Issue by alexpls** [mailosaur/mailosaur-node#12]
This commit (https://github.com/mailosaur/mailosaur-node/commit/951d0a4644d13bbb53bec0df26bd37ec9ae93d99) fixes Mailosaur client library usage with TypeScript. It was merged to `master` branch about 17 days ago, but hasn't been published to npm yet.

Could a new version of this module please be published to npm? This will enable TypeScript users to use the Mailosaur client library without having to resort to hacks.

Thanks!

**Comment by hippyhorse** [comment]
We've just kicked off a release build now, 5.0.8 should be live any minute now 👍

**Comment by alexpls** [comment]
That's perfect, thank you!
