### ISSUE TITLE
Trying to get a message when the mailbox is empty returns a 404 error

### ISSUE THREAD

**Issue by dennmart** [mailosaur/mailosaur-node#26]
I'm writing some tests using [TestCafe](https://devexpress.github.io/testcafe/) with the Mailosaur Node client. The client is working well for the most part but I'm running into an error when trying to get a message when the mailbox is empty.

For instance, I'm trying to fetch a message using the following, which is what's shown in the docs:

```javascript
let message = await client.messages.get("<server ID>", {
  sentTo: "test@email.com"
});
```

If the mailbox happens to be empty, I'm getting `Error: Operation returned an invalid status code '404'` from the Mailosaur client. The same code works as expected if the mailbox has at least one message that matches. 

My expectation was that the above code would keep waiting for an email until a match is found, which is what's written in the docs. I'm unsure whether this is a bug or I need to be doing something different. Out of curiosity, calling the API directly using Curl works as I would expect - it returns a 200 OK status code with an empty `items` array, not a 404.

Some relevant information from my development environment:

- Node v12.14.0 (also tested with Node v10.16.3)
- NPM v6.13.4
- Mailosaur Client v6.0.4
- TestCafe v1.7.1

Please let me know if you need any additional information.

**Comment by dennmart** [comment]
I dug around a bit in the source code and it seems like the root of the problem happens in https://github.com/mailosaur/mailosaur-node/blob/master/lib/operations/messages.js#L84. Searching in an empty mailbox returns an empty array, but the client proceeds with the call to `getById`. Since there's no ID, it raises the 404.

**Comment by andosaur** [comment]
@dennmart thanks for digging into this. We will investigate.

**Comment by hippyhorse** [comment]
@dennmart This method is working as designed; what you're seeing is the result of the `get` method looking for X length of time and then confirming nothing was found (therefore returning the correct `Not Found` http header). The `get` method is designed for the most common use case of 'positive path' scenarios (i.e. the specific message is expected to be found, and if it isn't then that's an error).

If you want to test the negative scenario you could add an exception assertion or, if instead you have a requirement to pass successfully even when there are no results, then per what you've seen when looking into the code, you can call the `search` method instead and only call `getById` if you want to get a particular result.

Alternative if you just want to wait longer for your result, you can pass in a longer wait time ([see here](https://docs.mailosaur.com/docs/fetching-messages#section-changing-the-default-timeout))

I will update our documentation to make this operation clearer.

**Comment by hippyhorse** [comment]
[Documentation updated](https://docs.mailosaur.com/docs/fetching-messages#section-finding-the-most-recent-message).
