### ISSUE TITLE
Request library is deprecated

### ISSUE THREAD

**Issue by shawn-rival** [mailosaur/mailosaur-node#32]
As of Feb 11th 2020, `request` is fully deprecated. Any plans to migrate off it? This wouldn't be too big of an issue but this lib depends on a version of `request` that depends on a version of `tough-cookie` that is missing a dependency (`net`), so you're required to manually add that. This was fixed in v3.0.0 of `tough-cookie` but `request` is no longer accepting PR's so this probably won't get fixed. 

Let me know if I can help!

**Comment by hippyhorse** [comment]
Hey @shawn-rival, thanks for raising this. We'd probably favour removing `request` all together and creating an internal class that leverages `fetch` instead.

We can add this to our backlog, but it might take a few weeks to get this done, unless you fancy submitting a PR to this effect?
