### ISSUE TITLE
Mark Unread Messages

### ISSUE THREAD

**Issue by bzthunter** [mailosaur/mailosaur-node#57]
How to marked the unread messages on mailosaur. 
I tried mailosaur.messages.update but not working is it updated?

**Comment by hippyhorse** [comment]
Hi there,

Its not currently possible to mark messages read/unread via the API - for now the best solution is the use `receivedAfter` option to limit the results you get back: https://mailosaur.com/docs/languages/nodejs/#5-narrowing-your-search-results

If you need further help, just contact support via the website.
