### ISSUE TITLE
Some URLs have "null" appended when no query string is provided

### ISSUE THREAD

**Issue by nibblesnbits** [mailosaur/mailosaur-node#64]
I've discovered that in some contexts (in my case, running in Cypress), that requests such as ones called by `getById` have the string "null" appended to the path because the `search` property of the URL is null.  [This line](https://github.com/mailosaur/mailosaur-node/blob/master/lib/request.js#L78) is the culprit.  I'm submitting a pull request shortly with the fix, which is simply a fallback to an empty string.

**Comment by jm-mailosaur** [comment]
Thanks @nibblesnbits, this is now incorporated into version `8.6.1`. Just incase you didn't realise, we also have a dedicated [Cypress plugin](https://github.com/mailosaur/cypress-mailosaur) that may be of use if you're working with Cypress.

**Comment by nibblesnbits** [comment]
I didn't know about that.  Thanks!
