### ISSUE TITLE
SMS latency

### ISSUE THREAD

**Issue by ivanovicuros** [mailosaur/mailosaur-node#67]
Hi there,

I have an issue with SMS latency, even after pausing the test for 5s still not able to obtain the message from the server, while the email works perfectly fine SMS does not - US number

Node v18.12.1

**Comment by jm-mailosaur** [comment]
Hi @ivanovicuros, please direct this kind of query to our [support team](https://mailosaur.com/contact) as this isn't related to the API client itself, rather is a product support query.

**Comment by ivanovicuros** [comment]
thanks @jm-mailosaur
