### ISSUE TITLE
Question: request to 34.149.187.159:443

### ISSUE THREAD

**Issue by MartinPilny** [mailosaur/mailosaur-node#70]
Hello,
I would like to know under which circumstances can mailosaur library send request to 34.149.187.159:443.

We noticed it during run of our Playwright test suite today, when one of tests failed on
`Error: connect ETIMEDOUT 34.149.187.159:443`

due to our company new firewall rules.

Sample of code we use:
```ts
// ...

const mailosaurClient = new Mailosaur(mailosaurApiKey)
await mailosaurClient.messages.search(mailosaurServerId, criteria, options)

// ...
```
Versions:
mailosaur-node: 8.6.1
playwright: 1.45.3

**Comment by jm-mailosaur** [comment]
This is the IP address of `https://mailosaur.com` and so will be called whenever an API call is made to the Mailosaur API. In your code sample there, it will be called when `.search` is invoked.

**Comment by MartinPilny** [comment]
but calling directly IP with port 443? It is weird, isn't it?

**Comment by jm-mailosaur** [comment]
Indeed it would be, our code does not call the IP address directly, you can see this in [the source code](https://github.com/mailosaur/mailosaur-node/blob/main/lib/request.js#L8) and by searching this repo for any references to the IP address.

What you're seeing is Node.js or openssl itself outputting an error *after* a DNS lookup on the domain name.
